version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://todo_user:todo_password@db:3306/todo_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - my_network
networks:
  my_network:


volumes:
  mysql_data:
